AWSTemplateFormatVersion: 2010-09-09
Description: >
  games.bradfordly.com stack

Parameters:
  EnvironmentName:
    Type: String
    Description: A short name for the environment (e.g. dev, prod, feature123)
    AllowedPattern: "^(dev|prod|feature[0-9]{3})$"
    ConstraintDescription: |
      Must be one of the following:
      - 'feature' followed by 3 digits that corresond to an issue number on github (e.g. feature001, feature010, feature101)
      - 'dev' for the development branch
      - 'prod' for the current release branch
  
  Component:
    Type: String
    Description: Component name for tagging resources
  
  Owner:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Description: Owner contact for tagging resources
    Default: '/gamehost/owner'
  
  LatestAmiId:
    Type: 
    Description: The latest available AMI ID for the host os
    Default: '/gamehost/latestAmiId'

  FQDN:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Fully Qualified Domain Name for the host
    Default: '/gamehost/fqdn'
  
  S3StagingBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: S3 staging bucket for scripts, backups, and other assets
    Default: '/gamehost/s3bucket'

  CognitoDomainPrefix:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: >
      Unique prefix for Cognito hosted UI domain (e.g. mygameapp).
      Must be globally unique within Cognito hosted domains.
    Default: '/gameUI/cognitoDomainPrefix'

  WebAppCallbackUrl:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: OAuth2 callback URL
    Default: '/gameUI/webAppCallbackUrl'
  
  WebAppLogoutUrl:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Post-logout URL
    Default: '/gameUI/webAppLogoutUrl'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      # - Label:
      #     default: Existing Networking
      #   Parameters:
      #     - VpcId
      #     - Subnet1Id
      #     - Subnet2Id
      - Label:
          default: Cognito
        Parameters:
          - CognitoDomainPrefix
          - WebAppCallbackUrl
          - WebAppLogoutUrl

Resources:
  #######################################
  # Access
  #######################################

  GamehostIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Component}-gamehost-role-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Component
          Value: !Ref Component
        - Key: Owner
          Value: !Ref Owner
  
  GamehostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !GetAtt GamehostIAMRole.Arn

  #######################################
  # Compute
  #######################################

  GamehostEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref GamehostInstanceProfile
      SecurityGroups:
        - !Ref GamehostSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            aws s3 cp ${S3StagingBucket}/scripts/gamehost /opt/gamehost/scripts
            chmod +x /opt/gamehost/scripts/gamehost-userdata.sh
            export FQDN="${FQDN:-localhost}"
            export MYSQL_DB="panel"
            export MYSQL_USER="pterodactyl"
            export MYSQL_PASSWORD="TestPassword123!"
            export timezone="America/New_York"
            export ASSUME_SSL="false"
            export CONFIGURE_LETSENCRYPT="false"
            export CONFIGURE_FIREWALL="true"
            export email="admin@example.com"
            export user_email="admin@example.com"
            export user_username="admin"
            export user_firstname="Admin"
            export user_lastname="User"
            export user_password="TestAdminPassword123!"
            bash . /opt/gamehost/scripts/gamehost-userdata.sh
      InstanceType: m5.large
      ImageId: !Ref LatestAmiId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: '30'
            DeleteOnTermination: 'true'
            Encrypted: 'true'
      Tags:
        - Key: Name
          Value: !Sub "${Component}-gamehost-ec2-${Environment}"

  #######################################
  # Networking
  #######################################
  
  GamehostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupName: "games-stack-gamehost-ec2-access"
        GroupDescription: "Allows specific traffic in/out for SSH and game servers"
        SecurityGroupIngress:
          - IpProtocol: udp
            FromPort: 27015
            ToPort: 27015
            CidrIp: 0.0.0.0/0
            Description: Steam
          - IpProtocol: tcp
            FromPort: 25565
            ToPort: 25565
            CidrIp: 0.0.0.0/0
            Description: Minecraft
          - IpProtocol: udp
            FromPort: 8211
            ToPort: 8211
            CidrIp: 0.0.0.0/0
            Description: Palworld
          - IpProtocol: tcp
            FromPort: 1985
            ToPort: 1985
            CidrIp: 0.0.0.0/0
            Description: Palworld2

  #######################################
  # Data
  #######################################
  
  # GamehostUIS3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub "games.bradfordly.com" # TODO: add conditional based on EnvironmentName
  #     VersioningConfiguration:
  #       Status: Enabled

  # GamehostUIDynamoDBTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub "games-stack-ddb-${EnvironmentName}"
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH

  #######################################
  # Cognito User Pool (User Login)
  #######################################

  # TODO: Set up Cognito after serverless UI is ready - this will move to games-ui module

  # CognitoUserPool:
  #   Type: AWS::Cognito::UserPool
  #   Properties:
  #     UserPoolName: !Sub "games-stack-user-pool-${EnvironmentName}"
  #     AutoVerifiedAttributes:
  #       - email
  #     Policies:
  #       PasswordPolicy:
  #         MinimumLength: 8
  #         RequireLowercase: true
  #         RequireNumbers: true
  #         RequireSymbols: false
  #         RequireUppercase: true
  #     Schema:
  #       - Name: email
  #         Required: true
  #         Mutable: true
  #     AccountRecoverySetting:
  #       RecoveryMechanisms:
  #         - Name: verified_email
  #           Priority: 1

  # CognitoUserPoolClient:
  #   Type: AWS::Cognito::UserPoolClient
  #   Properties:
  #     ClientName: !Sub "${EnvironmentName}-webapp-client"
  #     UserPoolId: !Ref CognitoUserPool
  #     GenerateSecret: false
  #     AllowedOAuthFlowsUserPoolClient: true
  #     AllowedOAuthFlows:
  #       - code
  #     AllowedOAuthScopes:
  #       - email
  #       - openid
  #       - profile
  #     CallbackURLs:
  #       - !Ref WebAppCallbackUrl
  #     LogoutURLs:
  #       - !Ref WebAppLogoutUrl
  #     SupportedIdentityProviders:
  #       - COGNITO
  #     PreventUserExistenceErrors: ENABLED
  #     ExplicitAuthFlows:
  #       - ALLOW_REFRESH_TOKEN_AUTH
  #       - ALLOW_USER_SRP_AUTH

  # CognitoUserPoolDomain:
  #   Type: AWS::Cognito::UserPoolDomain
  #   Properties:
  #     Domain: !Ref CognitoDomainPrefix
  #     UserPoolId: !Ref CognitoUserPool

  #######################################
  # Route53
  #######################################

  # TODO: create conditional based on EnvironmentName so that dev names it "games-dev.bradfordly.com" and prod names it "games.bradfordly.com"
  
  GamehostARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${EnvironmentName}.games.bradfordly.com"
      Type: A
      AliasTarget:
        HostedZoneId: !Ref HostedZoneId
        DNSName: !GetAtt GamehostEC2Instance.PublicDnsName
      HostedZoneId: !Ref HostedZoneId

Outputs:
  # VpcIdOut:
  #   Description: VPC ID used by the cluster
  #   Value: !Ref VpcId

  # SubnetIdsOut:
  #   Description: Subnets used by the cluster/nodegroup
  #   Value: !Join
  #     - ","
  #     - - !Ref SubnetId1
  #       - !Ref SubnetId2

  # CognitoUserPoolId:
  #   Description: Cognito User Pool ID
  #   Value: !Ref CognitoUserPool

  # CognitoUserPoolClientId:
  #   Description: Cognito User Pool Client ID
  #   Value: !Ref CognitoUserPoolClient

  # CognitoHostedUIDomain:
  #   Description: Cognito hosted UI domain base URL
  #   Value: !Sub "https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
