AWSTemplateFormatVersion: 2010-09-09
Description: >
  games.bradfordly.com stack

Parameters:
  Component:
    Type: String
    Default: games-stack
    Description: Component name for tagging resources
  
  Owner:
    Type: String
    Default: brad@bradfordly
    Description: Owner contact for tagging resources
  
  EnvironmentName:
    Type: String
    Default: dev
    Description: A short name for the environment (e.g. dev, prod)
    AllowedValues:
      - dev
      - prod

  ClusterName:
    Type: String
    Default: games-stack-eks-cluster
    Description: EKS cluster name

  KubernetesVersion:
    Type: String
    Default: "1.34"
    AllowedValues:
      - "1.34"
      - "1.33"
      - "1.32"
      - "1.31"
      - "1.30"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the existing VPC (e.g. your default VPC)

  Subnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: First subnet in the VPC (tag appropriately for EKS/ALB)
    
  Subnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Second subnet in the VPC (tag appropriately for EKS/ALB)

  CognitoDomainPrefix:
    Type: String
    Description: >
      Unique prefix for Cognito hosted UI domain (e.g. mygameapp).
      Must be globally unique within Cognito hosted domains.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "^[a-z0-9-]+$"

  WebAppCallbackUrl:
    Type: String
    Description: OAuth2 callback URL (e.g. https://example.com/oauth2/idpresponse)
  
  WebAppLogoutUrl:
    Type: String
    Description: Post-logout URL (e.g. https://example.com/)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment
        Parameters:
          - EnvironmentName
          - ClusterName
          - KubernetesVersion
      - Label:
          default: Existing Networking
        Parameters:
          - VpcId
          - Subnet1Id
          - Subnet2Id
      - Label:
          default: Cognito
        Parameters:
          - CognitoDomainPrefix
          - WebAppCallbackUrl
          - WebAppLogoutUrl

Resources:
  #######################################
  # IAM Roles
  #######################################

  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-role-${EnvironmentName}"
        - Key: Component
          Value: !Ref Component
        - Key: Owner
          Value: !Ref Owner

  FargateExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks-fargate-pods.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-fargate-execution-role-${EnvironmentName}"
        - Key: Component
          Value: !Ref Component
        - Key: Owner
          Value: !Ref Owner

  #######################################
  # EKS Cluster & Node Group
  #######################################

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${ClusterName}-${EnvironmentName}"
      RoleArn: !GetAtt EksClusterRole.Arn
      Version: !Ref KubernetesVersion
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
      Tags:
        - Key: Component
          Value: !Ref Component
        - Key: Owner
          Value: !Ref Owner

  #######################################
  # Cognito User Pool (User Login)
  #######################################

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "games-stack-user-pool-${EnvironmentName}"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${EnvironmentName}-webapp-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Ref WebAppCallbackUrl
      LogoutURLs:
        - !Ref WebAppLogoutUrl
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref CognitoUserPool

Outputs:
  VpcIdOut:
    Description: VPC ID used by the cluster
    Value: !Ref VpcId

  SubnetIdsOut:
    Description: Subnets used by the cluster/nodegroup
    Value: !Join
      - ","
      - - !Ref Subnet1Id
        - !Ref Subnet2Id

  EksClusterName:
    Description: EKS cluster name
    Value: !Ref EksCluster

  EksClusterArn:
    Description: EKS cluster ARN
    Value: !GetAtt EksCluster.Arn

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient

  CognitoHostedUIDomain:
    Description: Cognito hosted UI domain base URL
    Value: !Sub "https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
